micronaut:
  application:
    name: usermanagementsystem
  server:
    port: 8080
  security:
    enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      openapi:
        paths: classpath:META-INF/swagger
        mapping: /openapi/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/usermanagement
    username: postgres
    password: admin123
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    poolName: "HikariPool-1"
    maximumPoolSize: 5
    minimumIdle: 1
    idleTimeout: 300000
    connectionTimeout: 30000
    maxLifetime: 1200000

jpa:
  default:
    entity-scan:
      packages: "com.yash.usermanagementsystem"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          jdbc:
            driver: org.postgresql.Driver
    repositories:
      enabled: true

test-resources:
  enabled: false