micronaut:
  application:
    name: user-management
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8080
  data:
    jdbc:
      repositories:
        enabled: true
      default:
        enabled: true
        dialect: POSTGRES
        schema-generate: CREATE
        schema-generate-sources: CLASSES
        schema-generate-databases: true
        schema-generate-create: true
        schema-generate-drop: true
        schema-generate-create-sources: CLASSES
        schema-generate-drop-sources: CLASSES

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/usermanagement
    username: postgres
    password: admin123
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate:
      create: true
      use-foreign-keys: true
    db-type: postgres
    poolName: HikariPool
    maximumPoolSize: 10
    minimumIdle: 5
    idleTimeout: 300000
    connectionTimeout: 20000
    maxLifetime: 1200000
    validationQuery: "SELECT 1"
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    jmxEnabled: true

openapi:
  title: User Management API
  version: 1.0
  description: API for managing users and their addresses 